# Generated by Django 4.1.1 on 2022-09-30 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Місто')),
            ],
        ),
        migrations.CreateModel(
            name='AddCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('published', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('wifi', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='addcard.city')),
            ],
        ),
    ]
